/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Batsman {
  'name' : string,
  'runs' : bigint,
  'dismissals' : [] | [Dismissal],
  'strikeRate' : number,
  'ballsFaced' : bigint,
  'retired' : boolean,
}
export interface Bowler {
  'overs' : bigint,
  'name' : string,
  'wickets' : bigint,
  'balls' : bigint,
  'economyRate' : number,
  'runsConceded' : bigint,
}
export interface Dismissal { 'description' : string, 'batsman' : string }
export interface Innings {
  'bowlers' : Array<Bowler>,
  'overs' : bigint,
  'totalScore' : bigint,
  'wickets' : bigint,
  'extras' : {
    'byes' : bigint,
    'legByes' : bigint,
    'noBalls' : bigint,
    'wides' : bigint,
  },
  'batsmen' : Array<Batsman>,
}
export interface MatchAnalytics {
  'topScorer' : { 'name' : string, 'runs' : bigint },
  'bestEconomyRate' : { 'name' : string, 'rate' : number },
  'topWicketTaker' : { 'name' : string, 'wickets' : bigint },
  'highestStrikeRate' : { 'name' : string, 'rate' : number },
}
export interface MatchResult {
  'innings1' : Innings,
  'innings2' : Innings,
  'teamA' : string,
  'teamB' : string,
  'turns' : bigint,
  'teamBScore' : bigint,
  'overs' : bigint,
  'date' : [] | [string],
  'winner' : string,
  'tossInfo' : TossInfo,
  'teamAScore' : bigint,
}
export interface MatchStats {
  'teamA' : string,
  'teamB' : string,
  'teamARuns' : bigint,
  'winner' : string,
  'teamBRuns' : bigint,
}
export interface TossInfo { 'winningTeam' : string }
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearMatchHistory' : ActorMethod<[], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDateFilteredAnalytics' : ActorMethod<[string], [] | [MatchAnalytics]>,
  'getDateFilteredMatches' : ActorMethod<[string], Array<MatchResult>>,
  'getDateFilteredStats' : ActorMethod<[string], Array<MatchStats>>,
  'getDateGames' : ActorMethod<[string], bigint>,
  'getMatchAnalytics' : ActorMethod<[bigint], [] | [MatchAnalytics]>,
  'getMatchHistory' : ActorMethod<[], Array<MatchResult>>,
  'getMatchStats' : ActorMethod<
    [string],
    [string, string, bigint, bigint, string]
  >,
  'getMatches' : ActorMethod<[], Array<string>>,
  'getScorecard' : ActorMethod<[bigint], [] | [MatchResult]>,
  'getTeamMatches' : ActorMethod<[string], Array<MatchResult>>,
  'getTeamStats' : ActorMethod<[string], [bigint, bigint, bigint]>,
  'getTeams' : ActorMethod<[], Array<string>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'storeMatchOutcome' : ActorMethod<
    [
      string,
      string,
      bigint,
      string,
      bigint,
      bigint,
      bigint,
      TossInfo,
      Innings,
      Innings,
      [] | [string],
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];