/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const MatchAnalytics = IDL.Record({
  'topScorer' : IDL.Record({ 'name' : IDL.Text, 'runs' : IDL.Nat }),
  'bestEconomyRate' : IDL.Record({ 'name' : IDL.Text, 'rate' : IDL.Float64 }),
  'topWicketTaker' : IDL.Record({ 'name' : IDL.Text, 'wickets' : IDL.Nat }),
  'highestStrikeRate' : IDL.Record({ 'name' : IDL.Text, 'rate' : IDL.Float64 }),
});
export const Bowler = IDL.Record({
  'overs' : IDL.Nat,
  'name' : IDL.Text,
  'wickets' : IDL.Nat,
  'balls' : IDL.Nat,
  'economyRate' : IDL.Float64,
  'runsConceded' : IDL.Nat,
});
export const Dismissal = IDL.Record({
  'description' : IDL.Text,
  'batsman' : IDL.Text,
});
export const Batsman = IDL.Record({
  'name' : IDL.Text,
  'runs' : IDL.Nat,
  'dismissals' : IDL.Opt(Dismissal),
  'strikeRate' : IDL.Float64,
  'ballsFaced' : IDL.Nat,
  'retired' : IDL.Bool,
});
export const Innings = IDL.Record({
  'bowlers' : IDL.Vec(Bowler),
  'overs' : IDL.Nat,
  'totalScore' : IDL.Nat,
  'wickets' : IDL.Nat,
  'extras' : IDL.Record({
    'byes' : IDL.Nat,
    'legByes' : IDL.Nat,
    'noBalls' : IDL.Nat,
    'wides' : IDL.Nat,
  }),
  'batsmen' : IDL.Vec(Batsman),
});
export const TossInfo = IDL.Record({ 'winningTeam' : IDL.Text });
export const MatchResult = IDL.Record({
  'innings1' : Innings,
  'innings2' : Innings,
  'teamA' : IDL.Text,
  'teamB' : IDL.Text,
  'turns' : IDL.Nat,
  'teamBScore' : IDL.Nat,
  'overs' : IDL.Nat,
  'date' : IDL.Opt(IDL.Text),
  'winner' : IDL.Text,
  'tossInfo' : TossInfo,
  'teamAScore' : IDL.Nat,
});
export const MatchStats = IDL.Record({
  'teamA' : IDL.Text,
  'teamB' : IDL.Text,
  'teamARuns' : IDL.Nat,
  'winner' : IDL.Text,
  'teamBRuns' : IDL.Nat,
});

export const idlService = IDL.Service({
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearMatchHistory' : IDL.Func([], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDateFilteredAnalytics' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(MatchAnalytics)],
      ['query'],
    ),
  'getDateFilteredMatches' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MatchResult)],
      ['query'],
    ),
  'getDateFilteredStats' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MatchStats)],
      ['query'],
    ),
  'getDateGames' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getMatchAnalytics' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(MatchAnalytics)],
      ['query'],
    ),
  'getMatchHistory' : IDL.Func([], [IDL.Vec(MatchResult)], ['query']),
  'getMatchStats' : IDL.Func(
      [IDL.Text],
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Text],
      ['query'],
    ),
  'getMatches' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getScorecard' : IDL.Func([IDL.Nat], [IDL.Opt(MatchResult)], ['query']),
  'getTeamMatches' : IDL.Func([IDL.Text], [IDL.Vec(MatchResult)], ['query']),
  'getTeamStats' : IDL.Func([IDL.Text], [IDL.Nat, IDL.Nat, IDL.Nat], ['query']),
  'getTeams' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'storeMatchOutcome' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        TossInfo,
        Innings,
        Innings,
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const MatchAnalytics = IDL.Record({
    'topScorer' : IDL.Record({ 'name' : IDL.Text, 'runs' : IDL.Nat }),
    'bestEconomyRate' : IDL.Record({ 'name' : IDL.Text, 'rate' : IDL.Float64 }),
    'topWicketTaker' : IDL.Record({ 'name' : IDL.Text, 'wickets' : IDL.Nat }),
    'highestStrikeRate' : IDL.Record({
      'name' : IDL.Text,
      'rate' : IDL.Float64,
    }),
  });
  const Bowler = IDL.Record({
    'overs' : IDL.Nat,
    'name' : IDL.Text,
    'wickets' : IDL.Nat,
    'balls' : IDL.Nat,
    'economyRate' : IDL.Float64,
    'runsConceded' : IDL.Nat,
  });
  const Dismissal = IDL.Record({
    'description' : IDL.Text,
    'batsman' : IDL.Text,
  });
  const Batsman = IDL.Record({
    'name' : IDL.Text,
    'runs' : IDL.Nat,
    'dismissals' : IDL.Opt(Dismissal),
    'strikeRate' : IDL.Float64,
    'ballsFaced' : IDL.Nat,
    'retired' : IDL.Bool,
  });
  const Innings = IDL.Record({
    'bowlers' : IDL.Vec(Bowler),
    'overs' : IDL.Nat,
    'totalScore' : IDL.Nat,
    'wickets' : IDL.Nat,
    'extras' : IDL.Record({
      'byes' : IDL.Nat,
      'legByes' : IDL.Nat,
      'noBalls' : IDL.Nat,
      'wides' : IDL.Nat,
    }),
    'batsmen' : IDL.Vec(Batsman),
  });
  const TossInfo = IDL.Record({ 'winningTeam' : IDL.Text });
  const MatchResult = IDL.Record({
    'innings1' : Innings,
    'innings2' : Innings,
    'teamA' : IDL.Text,
    'teamB' : IDL.Text,
    'turns' : IDL.Nat,
    'teamBScore' : IDL.Nat,
    'overs' : IDL.Nat,
    'date' : IDL.Opt(IDL.Text),
    'winner' : IDL.Text,
    'tossInfo' : TossInfo,
    'teamAScore' : IDL.Nat,
  });
  const MatchStats = IDL.Record({
    'teamA' : IDL.Text,
    'teamB' : IDL.Text,
    'teamARuns' : IDL.Nat,
    'winner' : IDL.Text,
    'teamBRuns' : IDL.Nat,
  });
  
  return IDL.Service({
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearMatchHistory' : IDL.Func([], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDateFilteredAnalytics' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(MatchAnalytics)],
        ['query'],
      ),
    'getDateFilteredMatches' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MatchResult)],
        ['query'],
      ),
    'getDateFilteredStats' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MatchStats)],
        ['query'],
      ),
    'getDateGames' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getMatchAnalytics' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(MatchAnalytics)],
        ['query'],
      ),
    'getMatchHistory' : IDL.Func([], [IDL.Vec(MatchResult)], ['query']),
    'getMatchStats' : IDL.Func(
        [IDL.Text],
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Text],
        ['query'],
      ),
    'getMatches' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getScorecard' : IDL.Func([IDL.Nat], [IDL.Opt(MatchResult)], ['query']),
    'getTeamMatches' : IDL.Func([IDL.Text], [IDL.Vec(MatchResult)], ['query']),
    'getTeamStats' : IDL.Func(
        [IDL.Text],
        [IDL.Nat, IDL.Nat, IDL.Nat],
        ['query'],
      ),
    'getTeams' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'storeMatchOutcome' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          TossInfo,
          Innings,
          Innings,
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };