/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface MatchStats {
    teamA: string;
    teamB: string;
    teamARuns: bigint;
    winner: string;
    teamBRuns: bigint;
}
export interface MatchAnalytics {
    topScorer: {
        name: string;
        runs: bigint;
    };
    bestEconomyRate: {
        name: string;
        rate: number;
    };
    topWicketTaker: {
        name: string;
        wickets: bigint;
    };
    highestStrikeRate: {
        name: string;
        rate: number;
    };
}
export interface MatchResult {
    innings1: Innings;
    innings2: Innings;
    teamA: string;
    teamB: string;
    turns: bigint;
    teamBScore: bigint;
    overs: bigint;
    date?: string;
    winner: string;
    tossInfo: TossInfo;
    teamAScore: bigint;
}
export interface Bowler {
    overs: bigint;
    name: string;
    wickets: bigint;
    balls: bigint;
    economyRate: number;
    runsConceded: bigint;
}
export interface Innings {
    bowlers: Array<Bowler>;
    overs: bigint;
    totalScore: bigint;
    wickets: bigint;
    extras: {
        byes: bigint;
        legByes: bigint;
        noBalls: bigint;
        wides: bigint;
    };
    batsmen: Array<Batsman>;
}
export interface Dismissal {
    description: string;
    batsman: string;
}
export interface Batsman {
    name: string;
    runs: bigint;
    dismissals?: Dismissal;
    strikeRate: number;
    ballsFaced: bigint;
    retired: boolean;
}
export interface UserProfile {
    name: string;
}
export interface TossInfo {
    winningTeam: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    clearMatchHistory(): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDateFilteredAnalytics(date: string): Promise<MatchAnalytics | null>;
    getDateFilteredMatches(date: string): Promise<Array<MatchResult>>;
    getDateFilteredStats(date: string): Promise<Array<MatchStats>>;
    getDateGames(date: string): Promise<bigint>;
    getMatchAnalytics(matchId: bigint): Promise<MatchAnalytics | null>;
    getMatchHistory(): Promise<Array<MatchResult>>;
    getMatchStats(match: string): Promise<[string, string, bigint, bigint, string]>;
    getMatches(): Promise<Array<string>>;
    getScorecard(matchId: bigint): Promise<MatchResult | null>;
    getTeamMatches(team: string): Promise<Array<MatchResult>>;
    getTeamStats(team: string): Promise<[bigint, bigint, bigint]>;
    getTeams(): Promise<Array<string>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    storeMatchOutcome(teamA: string, teamB: string, overs: bigint, winner: string, turns: bigint, teamAScore: bigint, teamBScore: bigint, tossInfo: TossInfo, innings1: Innings, innings2: Innings, date: string | null): Promise<void>;
}
import type { Batsman as _Batsman, Bowler as _Bowler, Dismissal as _Dismissal, Innings as _Innings, MatchAnalytics as _MatchAnalytics, MatchResult as _MatchResult, TossInfo as _TossInfo, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async clearMatchHistory(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearMatchHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearMatchHistory();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDateFilteredAnalytics(arg0: string): Promise<MatchAnalytics | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDateFilteredAnalytics(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDateFilteredAnalytics(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDateFilteredMatches(arg0: string): Promise<Array<MatchResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDateFilteredMatches(arg0);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDateFilteredMatches(arg0);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDateFilteredStats(arg0: string): Promise<Array<MatchStats>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDateFilteredStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDateFilteredStats(arg0);
            return result;
        }
    }
    async getDateGames(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getDateGames(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDateGames(arg0);
            return result;
        }
    }
    async getMatchAnalytics(arg0: bigint): Promise<MatchAnalytics | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatchAnalytics(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatchAnalytics(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMatchHistory(): Promise<Array<MatchResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatchHistory();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatchHistory();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMatchStats(arg0: string): Promise<[string, string, bigint, bigint, string]> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatchStats(arg0);
                return [
                    result[0],
                    result[1],
                    result[2],
                    result[3],
                    result[4]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatchStats(arg0);
            return [
                result[0],
                result[1],
                result[2],
                result[3],
                result[4]
            ];
        }
    }
    async getMatches(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatches();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatches();
            return result;
        }
    }
    async getScorecard(arg0: bigint): Promise<MatchResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getScorecard(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScorecard(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeamMatches(arg0: string): Promise<Array<MatchResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeamMatches(arg0);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeamMatches(arg0);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeamStats(arg0: string): Promise<[bigint, bigint, bigint]> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeamStats(arg0);
                return [
                    result[0],
                    result[1],
                    result[2]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeamStats(arg0);
            return [
                result[0],
                result[1],
                result[2]
            ];
        }
    }
    async getTeams(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeams();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeams();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async storeMatchOutcome(arg0: string, arg1: string, arg2: bigint, arg3: string, arg4: bigint, arg5: bigint, arg6: bigint, arg7: TossInfo, arg8: Innings, arg9: Innings, arg10: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.storeMatchOutcome(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, to_candid_Innings_n18(this._uploadFile, this._downloadFile, arg8), to_candid_Innings_n18(this._uploadFile, this._downloadFile, arg9), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg10));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeMatchOutcome(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, to_candid_Innings_n18(this._uploadFile, this._downloadFile, arg8), to_candid_Innings_n18(this._uploadFile, this._downloadFile, arg9), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg10));
            return result;
        }
    }
}
function from_candid_Batsman_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Batsman): Batsman {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Innings_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Innings): Innings {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_MatchResult_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatchResult): MatchResult {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Dismissal]): Dismissal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MatchResult]): MatchResult | null {
    return value.length === 0 ? null : from_candid_MatchResult_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MatchAnalytics]): MatchAnalytics | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bowlers: Array<_Bowler>;
    overs: bigint;
    totalScore: bigint;
    wickets: bigint;
    extras: {
        byes: bigint;
        legByes: bigint;
        noBalls: bigint;
        wides: bigint;
    };
    batsmen: Array<_Batsman>;
}): {
    bowlers: Array<Bowler>;
    overs: bigint;
    totalScore: bigint;
    wickets: bigint;
    extras: {
        byes: bigint;
        legByes: bigint;
        noBalls: bigint;
        wides: bigint;
    };
    batsmen: Array<Batsman>;
} {
    return {
        bowlers: value.bowlers,
        overs: value.overs,
        totalScore: value.totalScore,
        wickets: value.wickets,
        extras: value.extras,
        batsmen: from_candid_vec_n12(_uploadFile, _downloadFile, value.batsmen)
    };
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    runs: bigint;
    dismissals: [] | [_Dismissal];
    strikeRate: number;
    ballsFaced: bigint;
    retired: boolean;
}): {
    name: string;
    runs: bigint;
    dismissals?: Dismissal;
    strikeRate: number;
    ballsFaced: bigint;
    retired: boolean;
} {
    return {
        name: value.name,
        runs: value.runs,
        dismissals: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.dismissals)),
        strikeRate: value.strikeRate,
        ballsFaced: value.ballsFaced,
        retired: value.retired
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    innings1: _Innings;
    innings2: _Innings;
    teamA: string;
    teamB: string;
    turns: bigint;
    teamBScore: bigint;
    overs: bigint;
    date: [] | [string];
    winner: string;
    tossInfo: _TossInfo;
    teamAScore: bigint;
}): {
    innings1: Innings;
    innings2: Innings;
    teamA: string;
    teamB: string;
    turns: bigint;
    teamBScore: bigint;
    overs: bigint;
    date?: string;
    winner: string;
    tossInfo: TossInfo;
    teamAScore: bigint;
} {
    return {
        innings1: from_candid_Innings_n10(_uploadFile, _downloadFile, value.innings1),
        innings2: from_candid_Innings_n10(_uploadFile, _downloadFile, value.innings2),
        teamA: value.teamA,
        teamB: value.teamB,
        turns: value.turns,
        teamBScore: value.teamBScore,
        overs: value.overs,
        date: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.date)),
        winner: value.winner,
        tossInfo: value.tossInfo,
        teamAScore: value.teamAScore
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Batsman>): Array<Batsman> {
    return value.map((x)=>from_candid_Batsman_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MatchResult>): Array<MatchResult> {
    return value.map((x)=>from_candid_MatchResult_n8(_uploadFile, _downloadFile, x));
}
function to_candid_Batsman_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Batsman): _Batsman {
    return to_candid_record_n22(_uploadFile, _downloadFile, value);
}
function to_candid_Innings_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Innings): _Innings {
    return to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bowlers: Array<Bowler>;
    overs: bigint;
    totalScore: bigint;
    wickets: bigint;
    extras: {
        byes: bigint;
        legByes: bigint;
        noBalls: bigint;
        wides: bigint;
    };
    batsmen: Array<Batsman>;
}): {
    bowlers: Array<_Bowler>;
    overs: bigint;
    totalScore: bigint;
    wickets: bigint;
    extras: {
        byes: bigint;
        legByes: bigint;
        noBalls: bigint;
        wides: bigint;
    };
    batsmen: Array<_Batsman>;
} {
    return {
        bowlers: value.bowlers,
        overs: value.overs,
        totalScore: value.totalScore,
        wickets: value.wickets,
        extras: value.extras,
        batsmen: to_candid_vec_n20(_uploadFile, _downloadFile, value.batsmen)
    };
}
function to_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    runs: bigint;
    dismissals?: Dismissal;
    strikeRate: number;
    ballsFaced: bigint;
    retired: boolean;
}): {
    name: string;
    runs: bigint;
    dismissals: [] | [_Dismissal];
    strikeRate: number;
    ballsFaced: bigint;
    retired: boolean;
} {
    return {
        name: value.name,
        runs: value.runs,
        dismissals: value.dismissals ? candid_some(value.dismissals) : candid_none(),
        strikeRate: value.strikeRate,
        ballsFaced: value.ballsFaced,
        retired: value.retired
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Batsman>): Array<_Batsman> {
    return value.map((x)=>to_candid_Batsman_n21(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
